modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="better_seeds"
version="0.1"
displayName="Better Seeds"
updateJSONURL="https://raw.githubusercontent.com/MitsukiGoto/MiknModVersions/master/BetterSeeds/versions.json"
# logoFile="examplemod.png"
authors="Mikn"
description='''
'''
[[dependencies.better_seeds]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.better_seeds]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"